package discord

import "time"

var GamePid int32

var DotaHeroes = map[string]map[string]string{
	"npc_dota_hero_abaddon":             {"name": "Abaddon", "img": "abaddon"},
	"npc_dota_hero_alchemist":           {"name": "Alchemist", "img": "alchemist"},
	"npc_dota_hero_antimage":            {"name": "Anti-Mage", "img": "antimage"},
	"npc_dota_hero_antimage_2":          {"name": "Anti-Mage", "img": "antimage"},
	"npc_dota_hero_ancient_apparition":  {"name": "Ancient Apparition", "img": "ancient_apparition"},
	"npc_dota_hero_arc_warden":          {"name": "Arc Warden", "img": "arc_warden"},
	"npc_dota_hero_axe":                 {"name": "Axe", "img": "axe"},
	"npc_dota_hero_axe_2":               {"name": "Axe", "img": "axe"},
	"npc_dota_hero_bane":                {"name": "Bane", "img": "bane"},
	"npc_dota_hero_batrider":            {"name": "Batrider", "img": "batrider"},
	"npc_dota_hero_beastmaster":         {"name": "Beastmaster", "img": "beastmaster"},
	"npc_dota_hero_bloodseeker":         {"name": "Bloodseeker", "img": "bloodseeker"},
	"npc_dota_hero_bounty_hunter":       {"name": "Bounty Hunter", "img": "bounty_hunter"},
	"npc_dota_hero_brewmaster":          {"name": "Brewmaster", "img": "brewmaster"},
	"npc_dota_hero_bristleback":         {"name": "Bristleback", "img": "bristleback"},
	"npc_dota_hero_broodmother":         {"name": "Broodmother", "img": "broodmother"},
	"npc_dota_hero_centaur":             {"name": "Centaur Warrunner", "img": "centaur"},
	"npc_dota_hero_chaos_knight":        {"name": "Chaos Knight", "img": "chaos_knight"},
	"npc_dota_hero_chen":                {"name": "Chen", "img": "chen"},
	"npc_dota_hero_clinkz":              {"name": "Clinkz", "img": "clinkz"},
	"npc_dota_hero_rattletrap":          {"name": "Clockwerk", "img": "rattletrap"},
	"npc_dota_hero_crystal_maiden":      {"name": "Crystal Maiden", "img": "crystal_maiden"},
	"npc_dota_hero_crystal_maiden_2":    {"name": "Crystal Maiden", "img": "crystal_maiden"},
	"npc_dota_hero_crystal_maiden_3":    {"name": "Crystal Maiden", "img": "crystal_maiden"},
	"npc_dota_hero_dark_seer":           {"name": "Dark Seer", "img": "dark_seer"},
	"npc_dota_hero_dark_willow":         {"name": "Dark Willow", "img": "dark_willow"},
	"npc_dota_hero_dawnbreaker":         {"name": "Dawnbreaker", "img": "dawnbreaker"},
	"npc_dota_hero_dazzle":              {"name": "Dazzle", "img": "dazzle"},
	"npc_dota_hero_death_prophet":       {"name": "Death Prophet", "img": "death_prophet"},
	"npc_dota_hero_disruptor":           {"name": "Disruptor", "img": "disruptor"},
	"npc_dota_hero_doom_bringer":        {"name": "Doom", "img": "doom_bringer"},
	"npc_dota_hero_dragon_knight":       {"name": "Dragon Knight", "img": "dragon_knight"},
	"npc_dota_hero_dragon_knight_2":     {"name": "Dragon Knight", "img": "dragon_knight"},
	"npc_dota_hero_drow_ranger":         {"name": "Drow Ranger", "img": "drow_ranger"},
	"npc_dota_hero_drow_ranger_2":       {"name": "Drow Ranger", "img": "drow_ranger"},
	"npc_dota_hero_drow_ranger_3":       {"name": "Drow Ranger", "img": "drow_ranger"},
	"npc_dota_hero_earth_spirit":        {"name": "Earth Spirit", "img": "earth_spirit"},
	"npc_dota_hero_earthshaker":         {"name": "Earthshaker", "img": "earthshaker"},
	"npc_dota_hero_earthshaker_2":       {"name": "Earthshaker", "img": "earthshaker"},
	"npc_dota_hero_earthshaker_3":       {"name": "Earthshaker", "img": "earthshaker"},
	"npc_dota_hero_elder_titan":         {"name": "Elder Titan", "img": "elder_titan"},
	"npc_dota_hero_ember_spirit":        {"name": "Ember Spirit", "img": "ember_spirit"},
	"npc_dota_hero_enchantress":         {"name": "Enchantress", "img": "enchantress"},
	"npc_dota_hero_enigma":              {"name": "Enigma", "img": "enigma"},
	"npc_dota_hero_faceless_void":       {"name": "Faceless Void", "img": "faceless_void"},
	"npc_dota_hero_faceless_void_2":     {"name": "Faceless Void", "img": "faceless_void"},
	"npc_dota_hero_faceless_void_3":     {"name": "Faceless Void", "img": "faceless_void"},
	"npc_dota_hero_grimstroke":          {"name": "Grimstroke", "img": "grimstroke"},
	"npc_dota_hero_gyrocopter":          {"name": "Gyrocopter", "img": "gyrocopter"},
	"npc_dota_hero_hoodwink":            {"name": "Hoodwink", "img": "hoodwink"},
	"npc_dota_hero_huskar":              {"name": "Huskar", "img": "huskar"},
	"npc_dota_hero_invoker":             {"name": "Invoker", "img": "invoker"},
	"npc_dota_hero_invoker_2":           {"name": "Invoker", "img": "invoker"},
	"npc_dota_hero_wisp":                {"name": "Io", "img": "wisp"},
	"npc_dota_hero_wisp_2":              {"name": "Io", "img": "wisp"},
	"npc_dota_hero_jakiro":              {"name": "Jakiro", "img": "jakiro"},
	"npc_dota_hero_juggernaut":          {"name": "Juggernaut", "img": "juggernaut"},
	"npc_dota_hero_juggernaut_2":        {"name": "Juggernaut", "img": "juggernaut"},
	"npc_dota_hero_juggernaut_3":        {"name": "Juggernaut", "img": "juggernaut"},
	"npc_dota_hero_keeper_of_the_light": {"name": "Keeper of the Light", "img": "keeper_of_the_light"},
	"npc_dota_hero_kez":                 {"name": "Kez", "img": "kez"},
	"npc_dota_hero_kunkka":              {"name": "Kunkka", "img": "kunkka"},
	"npc_dota_hero_legion_commander":    {"name": "Legion Commander", "img": "legion_commander"},
	"npc_dota_hero_legion_commander_2":  {"name": "Legion Commander", "img": "legion_commander"},
	"npc_dota_hero_leshrac":             {"name": "Leshracr", "img": "leshrac"},
	"npc_dota_hero_lich":                {"name": "Lich", "img": "lich"},
	"npc_dota_hero_life_stealer":        {"name": "Lifestealer", "img": "life_stealer"},
	"npc_dota_hero_lina":                {"name": "Lina", "img": "lina"},
	"npc_dota_hero_lina_2":              {"name": "Lina", "img": "lina"},
	"npc_dota_hero_lion":                {"name": "Lion", "img": "lion"},
	"npc_dota_hero_lone_druid":          {"name": "Lone Druid", "img": "lone_druid"},
	"npc_dota_hero_luna":                {"name": "Luna", "img": "luna"},
	"npc_dota_hero_lycan":               {"name": "Lycan", "img": "lycan"},
	"npc_dota_hero_magnataur":           {"name": "Magnus", "img": "magnataur"},
	"npc_dota_hero_marci":               {"name": "Marci", "img": "marci"},
	"npc_dota_hero_mars":                {"name": "Mars", "img": "mars"},
	"npc_dota_hero_medusa":              {"name": "Medusa", "img": "medusa"},
	"npc_dota_hero_meepo":               {"name": "Meepo", "img": "meepo"},
	"npc_dota_hero_mirana":              {"name": "Mirana", "img": "mirana"},
	"npc_dota_hero_mirana_2":            {"name": "Mirana", "img": "mirana"},
	"npc_dota_hero_monkey_king":         {"name": "Monkey King", "img": "monkey_king"},
	"npc_dota_hero_monkey_king_2":       {"name": "Monkey King", "img": "monkey_king"},
	"npc_dota_hero_morphling":           {"name": "Morphling", "img": "morphling"},
	"npc_dota_hero_muerta":              {"name": "Muerta", "img": "muerta"},
	"npc_dota_hero_naga_siren":          {"name": "Naga Siren", "img": "naga_siren"},
	"npc_dota_hero_furion":              {"name": "Nature's Prophet", "img": "furion"},
	"npc_dota_hero_necrolyte":           {"name": "Necrophos", "img": "necrolyte"},
	"npc_dota_hero_night_stalker":       {"name": "Night Stalker", "img": "night_stalker"},
	"npc_dota_hero_nyx_assassin":        {"name": "Nyx Assassin", "img": "nyx_assassin"},
	"npc_dota_hero_ogre_magi":           {"name": "Ogre Magi", "img": "ogre_magi"},
	"npc_dota_hero_ogre_magi_2":         {"name": "Ogre Magi", "img": "ogre_magi"},
	"npc_dota_hero_ogre_magi_3":         {"name": "Ogre Magi", "img": "ogre_magi"},
	"npc_dota_hero_omniknight":          {"name": "Omniknight", "img": "omniknight"},
	"npc_dota_hero_oracle":              {"name": "Oracle", "img": "oracle"},
	"npc_dota_hero_obsidian_destroyer":  {"name": "Outworld Destroyer", "img": "obsidian_destroyer"},
	"npc_dota_hero_pangolier":           {"name": "Pangolier", "img": "pangolier"},
	"npc_dota_hero_phantom_assassin":    {"name": "Phantom Assassin", "img": "phantom_assassin"},
	"npc_dota_hero_phantom_assassin_2":  {"name": "Phantom Assassin", "img": "phantom_assassin"},
	"npc_dota_hero_phantom_assassin_3":  {"name": "Phantom Assassin", "img": "phantom_assassin"},
	"npc_dota_hero_phantom_lancer":      {"name": "Phantom Lancer", "img": "phantom_lancer"},
	"npc_dota_hero_phoenix":             {"name": "Phoenix", "img": "phoenix"},
	"npc_dota_hero_primal_beast":        {"name": "Primal Beast", "img": "primal_beast"},
	"npc_dota_hero_puck":                {"name": "Puck", "img": "puck"},
	"npc_dota_hero_pudge":               {"name": "Pudge", "img": "pudge"},
	"npc_dota_hero_pudge_2":             {"name": "Pudge", "img": "pudge"},
	"npc_dota_hero_pudge_3":             {"name": "Pudge", "img": "pudge"},
	"npc_dota_hero_pudge_4":             {"name": "Pudge", "img": "pudge"},
	"npc_dota_hero_pugna":               {"name": "Pugna", "img": "pugna"},
	"npc_dota_hero_queenofpain":         {"name": "Queen of Pain", "img": "queenofpain"},
	"npc_dota_hero_queenofpain_2":       {"name": "Queen of Pain", "img": "queenofpain"},
	"npc_dota_hero_queenofpain_3":       {"name": "Queen of Pain", "img": "queenofpain"},
	"npc_dota_hero_razor":               {"name": "Razor", "img": "razor"},
	"npc_dota_hero_razor_2":             {"name": "Razor", "img": "razor"},
	"npc_dota_hero_razor_3":             {"name": "Razor", "img": "razor"},
	"npc_dota_hero_riki":                {"name": "Riki", "img": "riki"},
	"npc_dota_hero_ringmaster":          {"name": "Ringmaster", "img": "ringmaster"},
	"npc_dota_hero_rubick":              {"name": "Rubick", "img": "кubick"},
	"npc_dota_hero_rubick_2":            {"name": "Rubick", "img": "кubick"},
	"npc_dota_hero_sand_king":           {"name": "Sand King", "img": "sand_king"},
	"npc_dota_hero_shadow_demon":        {"name": "Shadow Demon", "img": "shadow_demon"},
	"npc_dota_hero_shadow_demon_2":      {"name": "Shadow Demon", "img": "shadow_demon"},
	"npc_dota_hero_nevermore":           {"name": "Shadow Fiend", "img": "nevermore"},
	"npc_dota_hero_nevermore_2":         {"name": "Shadow Fiend", "img": "nevermore"},
	"npc_dota_hero_shadow_shaman":       {"name": "Shadow Shaman", "img": "shadow_shaman"},
	"npc_dota_hero_silencer":            {"name": "Silencer", "img": "silencer"},
	"npc_dota_hero_skywrath_mage":       {"name": "Skywrath Mage", "img": "skywrath_mage"},
	"npc_dota_hero_slardar":             {"name": "Slardar", "img": "slardar"},
	"npc_dota_hero_slark":               {"name": "Slark", "img": "slark"},
	"npc_dota_hero_snapfire":            {"name": "Snapfire", "img": "snapfire"},
	"npc_dota_hero_sniper":              {"name": "Sniper", "img": "sniper"},
	"npc_dota_hero_spectre":             {"name": "Spectre", "img": "spectre"},
	"npc_dota_hero_spectre_2":           {"name": "Spectre", "img": "spectre"},
	"npc_dota_hero_spectre_3":           {"name": "Spectre", "img": "spectre"},
	"npc_dota_hero_spirit_breaker":      {"name": "Spirit Breaker", "img": "spirit_breaker"},
	"npc_dota_hero_storm_spirit":        {"name": "Storm Spirit", "img": "storm_spirit"},
	"npc_dota_hero_sven":                {"name": "Sven", "img": "sven"},
	"npc_dota_hero_techies":             {"name": "Techies", "img": "techies"},
	"npc_dota_hero_templar_assassin":    {"name": "Templar Assassin", "img": "templar_assassin"},
	"npc_dota_hero_terrorblade":         {"name": "Terrorblade", "img": "terrorblade"},
	"npc_dota_hero_terrorblade_2":       {"name": "Terrorblade", "img": "terrorblade"},
	"npc_dota_hero_tidehunter":          {"name": "Tidehunter", "img": "tidehunter"},
	"npc_dota_hero_shredder":            {"name": "Timbersaw", "img": "shredder"},
	"npc_dota_hero_tinker":              {"name": "Tinker", "img": "tinker"},
	"npc_dota_hero_tiny":                {"name": "Tiny", "img": "tiny"},
	"npc_dota_hero_treant":              {"name": "Treant Protector", "img": "treant"},
	"npc_dota_hero_troll_warlord":       {"name": "Troll Warlord", "img": "troll_warlord"},
	"npc_dota_hero_tusk":                {"name": "Tusk", "img": "tusk"},
	"npc_dota_hero_abyssal_underlord":   {"name": "Underlord", "img": "abyssal_underlord"},
	"npc_dota_hero_ursa":                {"name": "Ursa", "img": "ursa"},
	"npc_dota_hero_vengefulspirit":      {"name": "Vengeful Spirit", "img": "vengefulspirit"},
	"npc_dota_hero_venomancer":          {"name": "Venomancer", "img": "venomancer"},
	"npc_dota_hero_viper":               {"name": "Viper", "img": "viper"},
	"npc_dota_hero_visage":              {"name": "Visage", "img": "visage"},
	"npc_dota_hero_void_spirit":         {"name": "Void Spirit", "img": "void_spirit"},
	"npc_dota_hero_warlock":             {"name": "Warlock", "img": "warlock"},
	"npc_dota_hero_weaver":              {"name": "Weaver", "img": "weaver"},
	"npc_dota_hero_windrunner":          {"name": "Windranger", "img": "windrunner"},
	"npc_dota_hero_windrunner_2":        {"name": "Windranger", "img": "windrunner"},
	"npc_dota_hero_windrunner_3":        {"name": "Windranger", "img": "windrunner"},
	"npc_dota_hero_winter_wyvern":       {"name": "Winter Wyvern", "img": "winter_wyvern"},
	"npc_dota_hero_witch_doctor":        {"name": "Witch Doctor", "img": "witch_doctor"},
	"npc_dota_hero_skeleton_king":       {"name": "Wraith King", "img": "skeleton_king"},
	"npc_dota_hero_skeleton_king_2":     {"name": "Wraith King", "img": "skeleton_king"},
	"npc_dota_hero_skeleton_king_3":     {"name": "Wraith King", "img": "skeleton_king"},
	"npc_dota_hero_zuus":                {"name": "Zeus", "img": "zeus"},
	"npc_dota_hero_zuus_2":              {"name": "Zeus", "img": "zeus"},
}

var GameTime = time.Now()

var DotaGameState = map[string]string{
	"DOTA_GAMERULES_STATE_GAME_IN_PROGRESS": "В игре",
	"DOTA_GAMERULES_STATE_POST_GAME":        "Просматривает результаты игры",
	"DOTA_GAMERULES_STATE_HERO_SELECTION":   "Выбирает героя",
	"DOTA_GAMERULES_STATE_STRATEGY_TIME":    "Продумывает стратегию",
	"DOTA_GAMERULES_STATE_TEAM_SHOWCASE":    "Просмотр команд",
	"DOTA_GAMERULES_STATE_PRE_GAME":         "Загрузка игры",
}
